apiVersion: v1
kind: ConfigMap
metadata:
  name: global-demo
data:
  # property-like keys; each key maps to a simple value
  ui_properties_file_name: "user-interface.properties"

  # file-like keys
  middleware.properties: |
    db.type=mongo
    connections.maximum=1000   
  user-interface.properties: |
    color.good=green
    color.bad=red
    allow.textmode=true
