kind: Cluster
apiVersion: clusterregistry.k8s.io/v1alpha1
metadata:
  name: anthosaz-east1
  labels:
    environment: asm
---
kind: Cluster
apiVersion: clusterregistry.k8s.io/v1alpha1
metadata:
  name: gke-anthos-demo
  labels:
    environment: asm
